# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zuul}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Wes Gibbs"]
  s.date = %q{2009-11-04}
  s.description = %q{A simple authorization solution for Rails apps.}
  s.email = %q{wes@hashrocket.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/zuul.rb",
     "lib/zuul/restrict_access.rb",
     "lib/zuul/valid_roles.rb",
     "zuul.gemspec"
  ]
  s.homepage = %q{http://github.com/wgibbs/zuul}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple Rails Authorization}
  s.test_files = [
    "spec/rails_root",
     "spec/rails_root/app",
     "spec/rails_root/app/controllers",
     "spec/rails_root/app/controllers/application_controller.rb",
     "spec/rails_root/app/models",
     "spec/rails_root/app/models/user.rb",
     "spec/rails_root/config",
     "spec/rails_root/config/boot.rb",
     "spec/rails_root/config/database.yml",
     "spec/rails_root/config/environment.rb",
     "spec/rails_root/config/environments",
     "spec/rails_root/config/environments/test.rb",
     "spec/rails_root/config/initializers",
     "spec/rails_root/config/initializers/session_store.rb",
     "spec/rails_root/config/routes.rb",
     "spec/rails_root/db",
     "spec/rails_root/db/test.sqlite3",
     "spec/rails_root/log",
     "spec/rails_root/log/test.log",
     "spec/rails_root/spec",
     "spec/rails_root/spec/controllers",
     "spec/rails_root/spec/controllers/require_user_spec.rb",
     "spec/rails_root/spec/controllers/restrict_access_spec.rb",
     "spec/rails_root/spec/models",
     "spec/rails_root/spec/models/user_spec.rb",
     "spec/rails_root/spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

